"""
Assemble final video: concatenate stock clips to match voiceover length,
overlay burned-in captions generated by faster-whisper, mix in the voiceover.

Requires ffmpeg installed on the system (apt install ffmpeg / brew install ffmpeg).
"""
import subprocess
import os
import json
import math
from faster_whisper import WhisperModel

_whisper_model = None


def _get_whisper_model():
    global _whisper_model
    if _whisper_model is None:
        _whisper_model = WhisperModel("base", device="cpu", compute_type="int8")
    return _whisper_model


def _get_duration(path: str) -> float:
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        raise RuntimeError(f"Cannot get duration -- file is missing or empty: {path}")
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", path],
        capture_output=True, text=True,
    )
    duration_str = out.stdout.strip()
    if not duration_str:
        raise RuntimeError(
            f"ffprobe returned no duration for {path} (may be corrupt or not a "
            f"valid media file). ffprobe stderr: {out.stderr.strip()}"
        )
    return float(duration_str)


def _generate_captions_srt(audio_path: str, srt_path: str, orientation: str = "landscape"):
    """
    Generates short, punchy caption chunks (a few words at a time, TikTok/Shorts
    style) instead of whole-sentence blocks -- both more readable and avoids
    long lines wrapping into multiple rows that eat the screen.
    """
    max_chars = 22 if orientation == "portrait" else 42
    max_words = 4 if orientation == "portrait" else 7

    model = _get_whisper_model()
    segments, _ = model.transcribe(audio_path, word_timestamps=True)

    words = []
    for seg in segments:
        for w in seg.words:
            text = w.word.strip()
            if text:
                words.append((w.start, w.end, text))

    chunks = []
    buf = []
    for w in words:
        candidate = buf + [w]
        candidate_text = " ".join(x[2] for x in candidate)
        if buf and (len(candidate_text) > max_chars or len(candidate) > max_words):
            chunks.append(buf)
            buf = [w]
        else:
            buf = candidate
    if buf:
        chunks.append(buf)

    with open(srt_path, "w") as f:
        for i, chunk in enumerate(chunks, start=1):
            start = _format_srt_time(chunk[0][0])
            end = _format_srt_time(chunk[-1][1])
            text = " ".join(x[2] for x in chunk)
            f.write(f"{i}\n{start} --> {end}\n{text}\n\n")


def _format_srt_time(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def assemble_video(voiceover_path: str, clip_paths: list[str], output_path: str,
                    work_dir: str, orientation: str = "landscape") -> str:
    """
    orientation: "landscape" (1920x1080, standard videos) or
                 "portrait" (1080x1920, for YouTube Shorts).
    """
    os.makedirs(work_dir, exist_ok=True)
    voice_duration = _get_duration(voiceover_path)

    if orientation == "portrait":
        target_w, target_h = 1080, 1920
        caption_style = (f"FontSize=50,PrimaryColour=&HFFFFFF,OutlineColour=&H000000,"
                          f"BorderStyle=3,Outline=2,Shadow=0,MarginV=260,Alignment=2,"
                          f"PlayResX={target_w},PlayResY={target_h}")
    else:
        target_w, target_h = 1920, 1080
        caption_style = (f"FontSize=46,PrimaryColour=&HFFFFFF,OutlineColour=&H000000,"
                          f"BorderStyle=3,Outline=2,Shadow=0,MarginV=60,Alignment=2,"
                          f"PlayResX={target_w},PlayResY={target_h}")

    # 1. Build a concat list of clips, looping/trimming to roughly match voice length
    per_clip_duration = max(3.0, voice_duration / max(len(clip_paths), 1))
    trimmed_paths = []
    for i, clip in enumerate(clip_paths):
        trimmed = os.path.join(work_dir, f"trimmed_{i}.mp4")
        subprocess.run([
            "ffmpeg", "-y", "-i", clip, "-t", str(per_clip_duration),
            "-vf", f"scale={target_w}:{target_h}:force_original_aspect_ratio=increase,crop={target_w}:{target_h}",
            "-an", trimmed,
        ], check=True, capture_output=True)
        trimmed_paths.append(trimmed)

    concat_list_path = os.path.join(work_dir, "concat_list.txt")
    with open(concat_list_path, "w") as f:
        for p in trimmed_paths:
            f.write(f"file '{os.path.abspath(p)}'\n")

    concatenated = os.path.join(work_dir, "concatenated.mp4")
    subprocess.run([
        "ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", concat_list_path,
        "-c", "copy", concatenated,
    ], check=True, capture_output=True)

    # Source stock clips are sometimes shorter than the slice we asked for --
    # ffmpeg's -t just outputs whatever the source actually has, it doesn't pad.
    # If that leaves the concatenated reel shorter than the narration, the final
    # merge step below would otherwise truncate the AUDIO to match the shorter
    # video (cutting the voiceover off mid-sentence). Loop the reel to guarantee
    # it's at least as long as the narration before merging.
    concatenated_duration = _get_duration(concatenated)
    if concatenated_duration < voice_duration:
        loops_needed = math.ceil(voice_duration / concatenated_duration)
        looped = os.path.join(work_dir, "looped.mp4")
        subprocess.run([
            "ffmpeg", "-y", "-stream_loop", str(loops_needed - 1), "-i", concatenated,
            "-c", "copy", looped,
        ], check=True, capture_output=True)
        concatenated = looped

    # 2. Generate captions from the voiceover audio
    srt_path = os.path.join(work_dir, "captions.srt")
    _generate_captions_srt(voiceover_path, srt_path, orientation=orientation)

    # 3. Combine: trim video to voice length, mux audio, burn in captions
    subprocess.run([
        "ffmpeg", "-y",
        "-i", concatenated,
        "-i", voiceover_path,
        "-t", str(voice_duration),
        "-vf", f"subtitles={srt_path}:force_style='{caption_style}'",
        "-map", "0:v", "-map", "1:a",
        "-c:v", "libx264", "-c:a", "aac",
        output_path,
    ], check=True, capture_output=True)

    return output_path


if __name__ == "__main__":
    print("Run via main_pipeline.py -- this module expects prepared inputs.")
